### ISSUE TITLE
Zaptec Sense 

### ISSUE THREAD

**Issue by Bugs4Bugs** [sveinse/zaptec#14] opened 2023-09-16 15:02 UTC
Is it possible to add Zaptec Sense access. this is added to the HAN port of the el meter and provides information on current power use. 
It seems that the information is available in the API.

**Comment by sveinse** [comment] 2023-09-16 15:11
@Bugs4Bugs I don't have access to a Zaptec Sensr, so I don't really know what data it provides. I can take a look if you share a "Download diagnostics" that is available in any of the Zaptec devices. Thanks.

**Comment by Bugs4Bugs** [comment] 2023-09-16 15:34
Hi,

Appreciate your quick reply.
Not sure where I can download diagnostics.
The chart I see when I open https://portal.zaptec.com/ is as attached
picture.
It would be very helpful to use the Sense to monitor my power usage.

Thanks
Onno

Op za 16 sep 2023 om 17:12 schreef Svein Seldal ***@***.***>:

**Comment by sveinse** [comment] 2023-09-16 19:08
@Bugs4Bugs I assume you're running the new `zaptec-dev` right? Go to `Settings -> Devices & services -> Devices -> Aany zaptec device`. On the top left card there is a button named "Download diagnostics". Press it to download it and post it here please.

**Comment by Bugs4Bugs** [comment] 2023-09-16 19:22
Hi,

Please find the file attached. I do not find any references to the Zaptec
Sense though.
But please have a look and see what you find out. I am not the best with
programming, but I am a bad quiter.

Thanks for your time.

Op za 16 sep 2023 om 21:08 schreef Svein Seldal ***@***.***>:

**Comment by sveinse** [comment] 2023-09-16 19:25
@Bugs4Bugs I think I'm lacking the attachment. Please drag and drop the attachment in the web interface. Thanks.

**Comment by Bugs4Bugs** [comment] 2023-09-16 19:32
[home-assistant_zaptec_2023-09-16T19-17-46.940Z.log](https://github.com/sveinse/zaptec/files/12641449/home-assistant_zaptec_2023-09-16T19-17-46.940Z.log)

**Comment by sveinse** [comment] 2023-09-16 19:37
@Bugs4Bugs Thanks. Did you get that from the *zaptec* "Download diagnostics"? Because this seems more like the system logs, not the generated diagnostics dump from Zaptec. I deleted the comment, as it contained information you don't want out in the wild.

**Comment by Bugs4Bugs** [comment] 2023-09-16 19:46
Get a message that the file is not available on site.

**Comment by sveinse** [comment] 2023-09-16 19:52
Sorry, I don't understand. Let's take it from the beginning: Are you running the zaptec-dev version which is installed in HACS? Which version or id are you running?

**Comment by Bugs4Bugs** [comment] 2023-09-16 19:56
Running Zaptec-dev version 75df060

**Comment by sveinse** [comment] 2023-09-16 20:07
![image](https://github.com/sveinse/zaptec/assets/13770135/183fc13a-e1b1-41f7-bdc4-e4a3a1da3648)
![image](https://github.com/sveinse/zaptec/assets/13770135/5b6ab34e-e49a-42c6-a68b-b65cfaf90b9a)

**Comment by Bugs4Bugs** [comment] 2023-09-16 20:13
Not sure what is going on:
![Skjermbilde](https://github.com/sveinse/zaptec/assets/61287142/9b3b2416-5321-4f56-9cb2-046e7783c28a)
![Skjermbilde1](https://github.com/sveinse/zaptec/assets/61287142/2313d4cd-71ee-42cc-b9f4-455b77c7db13)

**Comment by sveinse** [comment] 2023-09-16 20:22
Strange indeed. It works with my HAs (and browser). I'm not sure what this is either. What happens if you hit "Resume"?

**Comment by Bugs4Bugs** [comment] 2023-09-16 20:34
The download start again when I press resume, but nothing happens. 
I installed the other Zaptec from Steffen integration from Steffen first, but removed that one.
Could this have some affect?

**Comment by sveinse** [comment] 2023-09-16 20:40
The official Zaptec integration must be uninstalled before installing zaptec-dev.

**Comment by Bugs4Bugs** [comment] 2023-09-16 20:41
Done that.  These are all the devices that are linked to zaptec -dev
![image](https://github.com/sveinse/zaptec/assets/61287142/d7798f36-6fbc-4367-8f0d-525322ad9068)

**Comment by sveinse** [comment] 2023-09-16 20:46
This all looks good 👍 . But the diagnostics download is having a bad day it seems. Have you tried another browser?

**Comment by Bugs4Bugs** [comment] 2023-09-16 20:48
Yes I did, same issue.

**Comment by sveinse** [comment] 2023-11-19 00:26
@Bugs4Bugs I know its been a while, are there any issues in the log that might indicate that the diagnostics doesn't work?

Otherwise, the official zaptec component is now released in beta 0.7.0. Perhaps this fixes the problem for you.

**Comment by Bugs4Bugs** [comment] 2023-11-19 13:35
Thanks for the feedback. I will try the 0.7.0 version

**Comment by sveinse** [comment] 2023-11-19 20:00
@Bugs4Bugs I've found an issue when generating the diagnostics download which I think is the root cause to the problems you've seen. If you download the official zaptec component from HACS and install the version "master", you'll get 0.7.1a1 which contains a fix for the diagnotics functions. Please install this and try again. I'm 🤞 my fingers and hope this works for you. Thanks.

**Comment by Bugs4Bugs** [comment] 2023-11-20 08:56
Updated Zaptec EV charger EV development, but still not able to download the diagnostics. Same issue. 
Not sure how to see which version I now installed.

**Comment by sveinse** [comment] 2023-11-20 19:57
@Bugs4Bugs are you using zaptec or zaptec-dev? The version can be read in HACS -> Integrations -> Zaptec EV Charger. The version is printed in the top left corner of the page.

**Comment by sveinse** [comment] 2023-12-29 14:18
Any news on this issue? I would like to close this issue in this development fork. The continued disussion about zaptec issues should be done in the official repo, https://github.com/custom-components/zaptec. Please post a issue here https://github.com/custom-components/zaptec/issues if this problem persists.

**Comment by Bugs4Bugs** [comment] 2023-12-29 14:46
Hi,

Please close the issue. I had contact with Zaptec, to see if the sense
could be added to the API.
For now they do not prioritize this.

**Closed** 2023-12-29 15:26 UTC
Labels: enhancement
